{"uuid": "90ee33e0-0a82-44f2-a308-34c25354dee9", "children": ["ccdf63c8-50b8-48f9-8fae-ed3b0f1ab603"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "NameError: name 'APK_PATH' is not defined\n", "trace": "  File \"C:\\Users\\Pramo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Pramo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Pramo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pramo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pramo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"F:\\K_R_F\\conftest.py\", line 23, in driver\n    options.app = APK_PATH  # Make sure this path is correct\n                  ^^^^^^^^\n"}, "start": 1751976792252, "stop": 1751976792252}], "start": 1751976792252, "stop": 1751976793427}